graph: default_graph

init_para:
  gamma: [0]
  beta: [0]

opt_method: COBYLA
# COBYLA, Nelder-Mead, Powell, CG, BFGS, Newton-CG, L-BFGS-B, TNC, SLSQP, trust-constr, dogleg, trust-ncg, trust-exact, trust-krylov















